name: power_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  async: ^2.11.0
  badges: ^3.1.2
  firebase_core: ^3.5.0
  firebase_database: ^11.1.3
  firebase_messaging: ^15.1.2
  flutter:
    sdk: flutter
  flutter_background_service: ^5.0.10
  flutter_local_notifications: ^17.2.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  provider: ^6.1.2
  push: ^2.3.0
  shared_preferences: ^2.3.2
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
