// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWPsPzsx8JExN0mByJm5Rb1a205q1njUk',
    appId: '1:691997881631:android:a288637f144192b1b4ac2a',
    messagingSenderId: '691997881631',
    projectId: 'powerprox-project',
    databaseURL: 'https://powerprox-project-default-rtdb.firebaseio.com',
    storageBucket: 'powerprox-project.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5WaaVYDCigOPBNetr-I-1Q1GiopIYAZU',
    appId: '1:691997881631:web:7915700e364115edb4ac2a',
    messagingSenderId: '691997881631',
    projectId: 'powerprox-project',
    authDomain: 'powerprox-project.firebaseapp.com',
    databaseURL: 'https://powerprox-project-default-rtdb.firebaseio.com',
    storageBucket: 'powerprox-project.appspot.com',
    measurementId: 'G-CX3XG9CFS3',
  );

}